services:
  - type: web
    name: mortalidad-colombia-2019
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server -c gunicorn.conf.py
    plan: free
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: "3.11.9"
